/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.alone.dts.thrift.struct;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class PublicStructConstants {

  public static final String CRON = "CRON";

  public static final String REAL_TIME = "REAL_TIME";

  public static final String TIMER = "TIMER";

  public static final String REPEAT = "REPEAT";

}
